"use client";

import Image from "next/image";
import { useState } from "react";

const serif = { fontFamily: "Georgia, 'Times New Roman', serif" };
const sans = { fontFamily: "Aptos, 'Segoe UI', sans-serif" };

export default function Home() {
  const [offerFormOpen, setOfferFormOpen] = useState(false);

  return (
    <main className="min-h-screen bg-[#fbf0df] pb-20 text-[#35281e] sm:pb-0" style={sans}>
      <section className="mx-auto grid max-w-6xl gap-7 px-5 pb-14 pt-28 sm:px-8 sm:pt-44 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:pb-20">
        <div>
          <p className="text-xs font-bold tracking-[0.26em] text-[#8a593d]">MANHASSET · LONG ISLAND</p>
          <h1 className="mt-4 max-w-3xl text-5xl leading-[.98] tracking-[-0.04em] sm:text-7xl" style={serif}>Laser hair removal that feels <em className="font-normal text-[#ae7c50]">personal.</em></h1>
          <p className="mt-6 max-w-xl text-lg leading-relaxed text-[#5b4638]">Safe, effective laser hair removal using FDA-approved Cynosure technology. Every treatment plan is personalized for your skin type, hair type, goals, and comfort—so you can feel confident from consultation to results.</p>
          <div className="mt-7 flex flex-col gap-3 sm:flex-row"><a className="rounded-xl bg-[#35281e] px-6 py-4 text-center font-bold text-white" href="tel:516-495-4908">Call Now · 516-495-4908</a><a className="rounded-xl border-2 border-[#35281e] bg-white px-6 py-4 text-center font-bold" href="sms:5166690634">Text Us</a></div>
          <div className="mt-7 flex flex-wrap gap-2 text-xs font-bold tracking-[0.1em] text-[#70432b]"><span className="rounded-full bg-white px-3 py-2">4.9★ GOOGLE REVIEWS</span><span className="rounded-full bg-white px-3 py-2">15+ YEARS</span><span className="rounded-full bg-white px-3 py-2">ALL SKIN TYPES</span></div>
        </div>
        <div className="rounded-[2rem] bg-[#fffdfb] p-5 shadow-xl sm:p-8">
          <Image alt="Optimum Laser" className="mx-auto h-auto w-36" height={92} src="/images/homepage/Optimum Laser Brown Logo.png" width={190} />
          <p className="mt-5 text-center text-xs font-bold tracking-[0.28em] text-[#8a593d]">NEW CLIENT SPECIAL</p>
          <div className="mt-4 divide-y divide-[#eadbcd] border-y border-[#eadbcd]"><div className="flex items-center gap-4 py-4"><strong className="font-serif text-5xl text-[#75472f]">$35</strong><span className="text-lg font-bold">Underarm Laser Hair Removal</span></div><div className="flex items-center gap-4 py-4"><strong className="font-serif text-5xl text-[#75472f]">$99</strong><span className="text-lg font-bold">Brazilian Laser Hair Removal</span></div></div>
          <p className="my-5 text-center text-lg" style={serif}>Your personalized laser journey starts here.</p>
          <button className="block w-full rounded-xl bg-[#ecd0ad] px-5 py-4 text-center font-bold text-[#4f2f1d]" onClick={() => setOfferFormOpen(true)} type="button">Claim My New Client Offer</button>
          {offerFormOpen && <form action={"https://formsubmit.co/" + process.env.NEXT_PUBLIC_EMAIL} className="mt-4 grid gap-2.5 border-t border-[#eadbcd] pt-4" method="POST"><input name="_next" type="hidden" value="https://optimumlaserhairremoval.com/thank-you?form=discount-popup" /><input name="_subject" type="hidden" value="New Client Special Lead" /><p className="text-center text-sm font-semibold">Tell us where to reach you to claim your new client discount.</p><label className="sr-only" htmlFor="offer-name">Name</label><input className="h-11 rounded-xl border border-[#e1c9b5] px-3" id="offer-name" name="name" placeholder="Name" required /><label className="sr-only" htmlFor="offer-email">Email</label><input className="h-11 rounded-xl border border-[#e1c9b5] px-3" id="offer-email" name="email" placeholder="Email" required type="email" /><label className="sr-only" htmlFor="offer-phone">Phone</label><input className="h-11 rounded-xl border border-[#e1c9b5] px-3" id="offer-phone" name="phone" placeholder="Phone" required type="tel" /><button className="rounded-xl bg-[#35281e] px-5 py-3 font-bold text-white" type="submit">Get My New Client Offer</button></form>}
          <p className="mt-3 text-center text-xs font-bold">Safe on all skin types. FDA-approved technology.</p>
        </div>
      </section>
      <section className="bg-white px-5 py-16 sm:px-8"><div className="mx-auto max-w-6xl"><p className="text-center text-xs font-bold tracking-[0.25em] text-[#8a593d]">THE OPTIMUM DIFFERENCE</p><h2 className="mx-auto mt-4 max-w-3xl text-center text-4xl leading-tight sm:text-6xl" style={serif}>Professional care.<br /><em className="font-normal text-[#ae7c50]">Proven results.</em></h2><p className="mx-auto mt-5 max-w-2xl text-center text-lg leading-relaxed text-[#5b4638]">For more than 15 years, Optimum Laser has combined advanced technology with careful, one-on-one guidance. We take time to understand your needs, explain your options, and help you choose a plan that feels right for you. <strong>We don&apos;t just treat clients—we treat them like family.</strong></p><div className="mt-10 grid gap-4 md:grid-cols-3">{[["Personalized", "We consider your skin tone, hair type, treatment area, sensitivity, and goals—because laser care should never be one-size-fits-all."], ["Advanced", "FDA-approved Cynosure technology helps us tailor safe, effective laser treatment for a broad range of skin types."], ["Trusted", "Our experienced team is known for a welcoming environment, honest guidance, and long-lasting client relationships."]].map(([title, copy], index) => <article className="rounded-2xl bg-[#fbf0df] p-7" key={title}><p className="text-xs font-bold tracking-[0.2em] text-[#ae7c50]">0{index + 1}</p><h3 className="mt-8 text-3xl" style={serif}>{title}</h3><p className="mt-3 leading-relaxed text-[#5b4638]">{copy}</p></article>)}</div></div></section>
      <section className="bg-[#f5e7d6] px-5 py-16 sm:px-8"><div className="mx-auto grid max-w-6xl gap-10 lg:grid-cols-[1fr_1.1fr] lg:items-center"><div><p className="text-xs font-bold tracking-[0.25em] text-[#8a593d]">YOUR FIRST VISIT</p><h2 className="mt-4 text-4xl leading-tight sm:text-5xl" style={serif}>A consultation should feel <em className="font-normal text-[#ae7c50]">easy.</em></h2><p className="mt-5 max-w-xl text-lg leading-relaxed text-[#5b4638]">We discuss your goals, recommend a plan that makes sense, and answer questions without pressure. You leave knowing exactly what your next step is.</p><a className="mt-7 inline-block rounded-xl bg-[#35281e] px-6 py-4 font-bold text-white" href="tel:516-495-4908">Book a Free Consultation</a></div><div className="grid gap-4 sm:grid-cols-2">{[["01 · LISTEN", "Your goals come first.", "Tell us what you would like to treat and what a successful result means to you."], ["02 · ASSESS", "A plan made for you.", "We consider your skin tone, hair type, treatment area, comfort level, and schedule."], ["03 · EXPLAIN", "Clear, honest guidance.", "You will understand treatment options, expected timing, and what to do next."], ["04 · CARE", "Like family, not a number.", "We don&apos;t just treat clients—we treat them like family throughout your journey."]].map(([label, title, copy], index) => <article className={index === 3 ? "rounded-2xl bg-[#35281e] p-6 text-white" : "rounded-2xl bg-white p-6 shadow-sm"} key={label}><p className={index === 3 ? "text-xs font-bold tracking-[0.18em] text-[#ecd0ad]" : "text-xs font-bold tracking-[0.18em] text-[#ae7c50]"}>{label}</p><h3 className="mt-4 text-2xl" style={serif}>{title}</h3><p className={index === 3 ? "mt-3 leading-relaxed text-[#eadbcd]" : "mt-3 leading-relaxed text-[#5b4638]"}>{copy}</p></article>))}</div></div></section>
      <section className="bg-white px-5 py-16 sm:px-8"><div className="mx-auto max-w-4xl"><p className="text-center text-xs font-bold tracking-[0.25em] text-[#8a593d]">COMMON QUESTIONS</p><h2 className="mt-4 text-center text-4xl sm:text-5xl" style={serif}>Before you book.</h2><p className="mx-auto mt-4 max-w-2xl text-center leading-relaxed text-[#5b4638]">Clear answers help you feel comfortable taking the next step.</p><div className="mt-8 divide-y divide-[#eadbcd] rounded-2xl border border-[#eadbcd] bg-[#fffdfb] px-6"><details className="py-5"><summary className="cursor-pointer font-bold">Is laser hair removal safe for my skin type?</summary><p className="mt-3 leading-relaxed text-[#5b4638]">Your consultation is where we discuss your skin, hair, treatment area, and goals. Optimum uses FDA-approved Cynosure technology and personalizes the treatment plan for you.</p></details><details className="py-5"><summary className="cursor-pointer font-bold">How many sessions will I need?</summary><p className="mt-3 leading-relaxed text-[#5b4638]">A minimum of 6 sessions is recommended. Some areas may need more sessions—it all depends on the treatment area, your hair growth, and your individual goals. Your provider will explain a personalized plan during your consultation.</p></details><details className="py-5"><summary className="cursor-pointer font-bold">What does treatment feel like?</summary><p className="mt-3 leading-relaxed text-[#5b4638]">Most clients describe a quick snapping sensation. We will explain what to expect and prioritize your comfort throughout the visit.</p></details><details className="py-5"><summary className="cursor-pointer font-bold">Can I call or text before booking?</summary><p className="mt-3 leading-relaxed text-[#5b4638]">Absolutely. Call us at 516-495-4908 or text us at 516-669-0634 with any questions.</p></details></div></div></section>
      <footer className="bg-[#35281e] px-5 py-14 text-[#fff9f2] sm:px-8"><div className="mx-auto grid max-w-6xl gap-8 md:grid-cols-2 lg:grid-cols-4"><div><Image alt="Optimum Laser" className="h-auto w-36 brightness-0 invert" height={70} src="/images/homepage/Optimum Laser Brown Logo.png" width={180} /><p className="mt-5 text-[#eadbcd]">1180 Northern Blvd, Suite 202<br />Manhasset, NY 11030</p></div><div><p className="text-xs font-bold tracking-[0.2em] text-[#ecd0ad]">SERVICES</p><nav className="mt-4 grid gap-3 text-[#eadbcd]"><a className="underline" href="/services/laser-service">Laser Hair Removal</a><a className="underline" href="/services/pigmentation-service">Pigmentation Removal</a><a className="underline" href="/services/vein-removal">Vein Removal</a><a className="underline" href="/services/facial-service">Facial Services</a></nav></div><div><p className="text-xs font-bold tracking-[0.2em] text-[#ecd0ad]">CONTACT</p><p className="mt-4 leading-loose text-[#eadbcd]"><a className="underline" href="tel:516-495-4908">Call 516-495-4908</a><br /><a className="underline" href="sms:5166690634">Text 516-669-0634</a><br /><a className="underline" href="mailto:optimumlaserhairremoval@gmail.com">Email us</a></p></div><div><p className="text-xs font-bold tracking-[0.2em] text-[#ecd0ad]">BUSINESS HOURS</p><p className="mt-4 leading-loose text-[#eadbcd]">Tue–Wed: 9am–6pm<br />Thu: 9am–8pm<br />Fri: 9am–3pm<br />Sun: 10am–5pm</p></div></div></footer>
      <div className="fixed inset-x-0 bottom-0 z-30 flex gap-2 border-t border-[#eadbcd] bg-white p-3 shadow-2xl sm:hidden"><a className="flex-1 rounded-xl bg-[#35281e] px-3 py-3 text-center font-bold text-white" href="tel:516-495-4908">Call Now</a><a className="flex-1 rounded-xl bg-[#ecd0ad] px-3 py-3 text-center font-bold" href="sms:5166690634">Text Us</a></div>
    </main>
  );
}
